### ISSUE TITLE
edge case acronyms and numbers

### ISSUE THREAD

**Issue by tofutim** [mrstebo/JsonSerializer.SnakeCase#3]
numbers with acronymns seem to give some issues

MyLLC1 -> my_ll_c_1
MyLLC11 -> my_ll_c_11

MyDog1 does work though

my second PR has the tests,

we may also want to peek at 

https://github.com/jonnii/emvelope/blob/master/src/Emvelope/Converters/SnakeCasePropertyNamesContractResolver.cs
https://gist.github.com/roryf/1042502

to see if there are some speed tests we can use

**Comment by mrstebo** [comment]
Acronyms are always a source of pain for serializers 😅. Again, I'll take a look tomorrow when I have a moment 👍

**Comment by tofutim** [comment]
it is not a big deal, I tried multiple snakes and yours was the best

**Comment by mrstebo** [comment]
The latest tag should fix this now. 

Now they will be changed like so:
- MyLLC1 -> my_llc1
- MyLLC11 -> my_llc11
